# Generated by Django 5.1.1 on 2024-09-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission',
            new_name='file',
        ),
    ]
